const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./index.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "Scraper API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    tags: [
        {
            "name": "Sites",
            "description": "Endpoints"
        },
        {
            "name": "Models",
            "description": "Endpoints"
        }
    ]
}

swaggerAutogen(outputFile, endpointsFiles, doc)